### ISSUE TITLE
修复MyStack中的bug

### ISSUE THREAD

**Issue by zjl9959** [zjl9959/GuillotineCut#1]
测试算例A17时，出现MyStack中索引出界bug。
分支：zjl
提交版本：SHA-1: a0657a8c11f90bda40df27ecc141a2cb7d6d7837

**Comment by lyandut** [comment]
- [x] 修复MyStack索引访问越界bug。

https://github.com/zjl9959/GuillotineCut/blob/a0657a8c11f90bda40df27ecc141a2cb7d6d7837/Solver/Algorithm.h#L127-L128

https://github.com/zjl9959/GuillotineCut/blob/b791949d38574f178e43ab647b9ba7acb2a186bb/Solver/Algorithm.h#L127-L128
