### ISSUE TITLE
寻找程序行为不确定的原因

### ISSUE THREAD

**Issue by zjl9959** [zjl9959/GuillotineCut#2]
在算例相同，随机种子相同，运行时间相同的情况下，程序输出的解有很大的差别。
问题代码版本：SHA-1: 9a422d6a3962f82c71518c76d8f3ef8d2a9bbd13
可能原因：
1.随机种子中间被改变？
2.没有调用指定的随机种子发生器？
3.多线程调度时间片不同导致？
注（在之前的版本SHA-1: e22b2ea5f9aa25a7e7e93ed967cf4c9346a7a5fd 中，并没有出现程序行为不确定的问题）。

**Comment by lyandut** [comment]
![image](https://user-images.githubusercontent.com/33196654/63581098-d0e04300-c5c8-11e9-953c-61f8c32be8aa.png)

- **分析：** 当规定时间设置较短时，`evaluateOnePlate()` 中的计时器可能会导致在规定时间内无法生成完整解（`eval_length` 数组中全是最大长度），而多线程完成顺序不同导致 `min_length` 可能对应随机一个 1-cut 解，相当于每次固定了最先超时的分支的 1-cut 解。

- **fix：** 删除 PlateSearch 中的计时器，只在顶层 `run()` 函数中控制超时。

**Comment by lyandut** [comment]
- **分析：** 测试逐一关闭程序中开启多线程的地方，只有在 1-cut 分支时开启多线程不会导致程序行为不确定，其他代码都是多线程中又开启多线程的情况。
https://github.com/zjl9959/GuillotineCut/blob/5f79b8a1dc62c6eff3456d37807db03d91766b3c/Solver/PlateSearch.cpp#L114-L115

- **fix：** 增加一个宏开关，关闭线程嵌套的代码。
https://github.com/zjl9959/GuillotineCut/blob/5f79b8a1dc62c6eff3456d37807db03d91766b3c/Solver/Algorithm.h#L133

**Comment by zjl9959** [comment]
程序行为不确定与多线程的时间片调度有关，同时运行的线程数不大于物理线程数可避免该情况。
