### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by zjl9959** [zjl9959/GuillotineCut#3]
https://github.com/zjl9959/GuillotineCut/blob/9a422d6a3962f82c71518c76d8f3ef8d2a9bbd13/Solver/Solver.cpp#L243
不是在找到更好的解的时候才固定一块原料，而是挑分支里面最好的解作为固定的原料。

**Comment by lyandut** [comment]
done
https://github.com/zjl9959/GuillotineCut/blob/5f79b8a1dc62c6eff3456d37807db03d91766b3c/Solver/Solver.cpp#L254-L265
